name: CI/CD Sphinx-Documentation
on: 
  push:
    branches:
      - main
      - Reworked_Docs_Integration

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install system dependencies for OpenGL
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install Code-Dependencies
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install -r requirements.txt
          pip install vispy
          pip install PySide6

      - name: Run version_carer.sh
        working-directory: docs
        run: |
          chmod +x version_carer.sh 
          ./version_carer.sh
      
      - name: Create conf.py for sphinx
        working-directory: docs
        run: |
          chmod +x sphinx_conf_builder.sh
          ./sphinx_conf_builder.sh

      - name: Create index.rst
        working-directory: docs
        run: |
          chmod +x master_index_builder.sh
          ./master_index_builder.sh
      
      - name: Build Docs
        working-directory: docs
        run: |
          sphinx-build -b html . build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
        





