name: Build and Deploy Sphinx Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - Docs_Integration
jobs:
  build:
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ['3.9', '3.10', '3.11', '3.12']

    runs-on: ${{ matrix.operating-system }}

    steps:
    - name: Check Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies for OpenGL
      if: matrix.operating-system == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx-rtd-theme
        pip install vispy
        pip install PySide6
        pip install -r requirements.txt
    
    - name: Prepare build-process of conf.py for creation of docs
      run: |
        cd docs
        chmod +x sphinx_doc_builder.sh
    
    - name: Create conf.py 
      shell: bash
      run: |
        cd docs
        ./sphinx_doc_builder.sh
    
    - name: Generate RST files with sphinx-apidoc
      run: |
        sphinx-apidoc -o docs/modules src/

    - name: Prepare build-process of index.rst
      shell: bash
      run: |
        cd docs
        chmod +x master_index_builder.sh
    
    - name: Generate Master index.rst
      shell: bash
      run: |
        cd docs
        ./master_index_builder.sh
        ls -la
        cat index.rst

    - name: Build Documentation with sphinx-build
      run: |
        cd docs
        sphinx-build -b html . _build/html
    
    - name: Push to gh-pages
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        git reset --hard
        rm -rf *
        cp -r docs/_build/html/* .
        git add .
        git commit -m "Update documentation via CI/CD"
        git push origin gh-pages --force