name: Build and Deploy Sphinx Documentation
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: 3.x

    runs-on: ${{ matrix.operating-system }}

    steps:
    - name: Check Repository
      uses: action/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
    - with:
      - python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install -r requirements.txt
    
    - name: Build docs
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .docs/docs/_build/html

