name: Testing & Profiling
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'profiling/**'

jobs:
  Unit-Testing:
    strategy: 
      matrix: 
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ['3.10', '3.11', '3.12']
    
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install system dependencies for OpenGL (Ubuntu-only)
        if: matrix.operatings_sys == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 

      - name: Run tests
        run: pytest
  
  Profiling:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 
          pip install snakeviz    
      
      - name: Install system dependencies for OpenGL
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1
       #  sudo apt-get install graphviz

      - name: Profile GUI and internal references
        run: |
          mkdir -p profiling
          python -m cProfile -o profiling/profiled.prof src/ParticleSystem.py 
      
      - name: Display code-profile
        working-directory: profiling
        run: python snakeviz_static_html.py profiled.prof

      - name: Deploy to main/profiling
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./profiling
          commit_message: automated-update-profiling-html
