name: Testing & Profiling
on:
  push:
    branches:
      - Testing

jobs:
  Unit-Testing:
    strategy: 
      matrix: 
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ['3.10', '3.11', '3.12']
    
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install system dependencies for OpenGL (Ubuntu-only)
        if: matrix.operatings_sys == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 

      - name: Run tests
        run: pytest