name: Testing & Profiling
on:
  push:
    branches:
      - Testing

jobs:
  Unit-Testing:
    strategy: 
      matrix: 
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ['3.10', '3.11', '3.12']
    
    runs-on: ${{ matrix.operating-system }}