name: Testing & Profiling
on:
  push:
    branches:
      - Testing

jobs:
  Unit-Testing:
    strategy: 
      matrix: 
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ['3.10', '3.11', '3.12']
    
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install system dependencies for OpenGL (Ubuntu-only)
        if: matrix.operatings_sys == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 

      - name: Run tests
        run: pytest
  
  Profiling:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 
          pip install snakeviz
      
      - name: Install system dependencies for OpenGL
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1
          apt-get install python-profiler

      - name: Profile GUI and internal references
        working-directory: src
        run: |
          mkdir -p profiling
          python -m cProfile -o ../profiling/profiled.dat GUI.py 
      
      - name: Display code-profile
        working-directory: profiling
        run: snakeviz --outfile=profile_code.html profiled.dat

      - name: Upload code profiling report as HTML
        uses: actions/upload-artifact@v4
        with:
          name: code-profiling-report
          path: profiling/profile_code.html